-- Rapid Cup — Phase 6 follow-up: close the "corrected result -> double
-- Winbox payout" gap found by re-testing after Phase 6 shipped.
--
-- THE BUG: collect_rapid_cup_winbox() re-derives the winner from the
-- fixture's CURRENT score every time it's called — it never freezes the
-- result at the moment of the original win. record_fixture_result is
-- explicitly designed (see 20260829_record_fixture_result_rpc.sql's own
-- header comment) to let an admin re-record an already-played fixture's
-- score to fix a mistake. Combine the two: Player A wins 2-1, collects 3
-- Nets. An admin later corrects the score to 1-2. Player A's 3 Nets are
-- never clawed back, and Player B — now the legitimate winner under the
-- corrected score — can collect their OWN 3 Nets, because the
-- double-collect guard on rapid_cup_collections is keyed per-user, not
-- per-fixture. Net result: two people get paid for one match.
--
-- This mirrors a bug class the league/knockout reward path already
-- avoids: _credit_league_fixture_reward / _credit_knockout_fixture_reward
-- both take a p_was_already_played flag from record_fixture_result and
-- simply refuse to run a second time on the same fixture. The Winbox
-- can't use that same trick as-is, because it isn't credited from
-- record_fixture_result at all — it's credited later, on demand, from a
-- player's own tap. So the fix has to live on the correction path
-- instead: once a Rapid Cup fixture has been collected, its result is
-- frozen. record_fixture_result and cancel_fixture_result both now
-- refuse to touch a Rapid Cup fixture that already has a winbox
-- collected against it (rapid_cup_collections.box_type = 'winbox') and
-- raise a clear error instead of silently allowing the double-pay.
--
-- Not a real-world exploit path for a normal player: only a genuine
-- platform admin can even reach this branch of record_fixture_result —
-- Rapid Cup's leagues.created_by is always null (rapid_cup leagues are
-- generated by generate_rapid_cup_bracket, never by a user "creating" a
-- league), so the league-creator branch of the authorization check can
-- never match anyone for a Rapid Cup fixture. Still a real, unaddressed
-- gap for a deliberate admin correction, which is exactly the scenario
-- record_fixture_result's own header comment says this path exists for.
--
-- Deliberately blocks rather than auto-clawing-back: an automatic
-- debit/re-credit on the affected users would be more "seamless" but
-- risks a wallet going negative or a user disputing a Nets deduction
-- they don't understand, for an admin-only edge case. Blocking with a
-- clear message ("this Winbox was already collected, so the result is
-- locked — resolve manually") is the safer default; an admin can still
-- adjust wallets by hand via the admin tools if a genuine correction is
-- needed after a Winbox has already paid out.
--
-- Rebuilt from each function's CURRENT live definition (both have
-- evolved since their original migration files — record_fixture_result
-- now also fires _credit_league_fixture_reward/_credit_knockout_fixture_reward,
-- and cancel_fixture_result now also allows a 30-minute self-cancel by
-- the poster) so this migration doesn't regress either of those.
--
-- Safe to run more than once.

create or replace function record_fixture_result(
  p_fixture_id uuid,
  p_home_score integer,
  p_away_score integer,
  p_pens_home integer default null,
  p_pens_away integer default null
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_fixture fixtures%rowtype;
  is_authorized boolean;
  v_was_already_played boolean;
begin
  select * into v_fixture from fixtures where id = p_fixture_id for update;
  if not found then
    raise exception 'Fixture % not found', p_fixture_id;
  end if;
  v_was_already_played := v_fixture.played;

  select
    exists (select 1 from leagues l where l.id = v_fixture.league_id and l.created_by = auth.uid())
    or exists (select 1 from admins a where a.user_id = auth.uid())
  into is_authorized;
  if not is_authorized then
    raise exception 'Only the league creator or an admin can record this result';
  end if;

  -- Rapid Cup Winbox correction guard (see header comment) — once a
  -- winner has tapped the Winbox for this fixture, the result is frozen.
  if exists (select 1 from rapid_cup_lobbies where league_id = v_fixture.league_id)
     and exists (select 1 from rapid_cup_collections where box_type = 'winbox' and ref_id = p_fixture_id)
  then
    raise exception 'This match''s Winbox has already been collected, so the result is locked and can''t be corrected here. Adjust wallets manually if a genuine correction is needed.';
  end if;

  if p_home_score is null or p_away_score is null then
    raise exception 'A score is required';
  end if;
  if p_home_score < 0 or p_away_score < 0
     or (p_pens_home is not null and p_pens_home < 0)
     or (p_pens_away is not null and p_pens_away < 0) then
    raise exception 'Scores cannot be negative';
  end if;
  if p_pens_home is not null and p_pens_away is not null and p_pens_home = p_pens_away then
    raise exception 'Penalty score cannot be level';
  end if;

  update fixtures set
    played = true,
    home_score = p_home_score,
    away_score = p_away_score,
    pens_home = p_pens_home,
    pens_away = p_pens_away,
    played_at = now()
  where id = p_fixture_id;

  perform _credit_league_fixture_reward(p_fixture_id, v_was_already_played);
  perform _credit_knockout_fixture_reward(p_fixture_id, v_was_already_played);
end;
$$;

create or replace function cancel_fixture_result(
  p_fixture_id uuid
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_fixture fixtures%rowtype;
  is_authorized boolean;
  v_self_cancel boolean;
begin
  select * into v_fixture from fixtures where id = p_fixture_id for update;
  if not found then
    raise exception 'Fixture % not found', p_fixture_id;
  end if;

  select
    exists (select 1 from leagues l where l.id = v_fixture.league_id and l.created_by = auth.uid())
    or exists (select 1 from admins a where a.user_id = auth.uid())
  into is_authorized;

  if not is_authorized then
    select exists (
      select 1 from comments
      where fixture_id = p_fixture_id
        and is_result = true
        and user_id = auth.uid()
        and created_at > now() - interval '30 minutes'
    ) into v_self_cancel;
    is_authorized := v_self_cancel;
  end if;

  if not is_authorized then
    raise exception 'Only the league creator, an admin, or the player who posted this result (within 30 minutes of posting) can cancel it';
  end if;

  if not v_fixture.played then
    raise exception 'This fixture has no result to cancel';
  end if;

  -- Rapid Cup Winbox correction guard (see header comment on
  -- record_fixture_result above) — cancelling would wipe the score a
  -- Winbox was already paid out against, same gap as a correction.
  if exists (select 1 from rapid_cup_lobbies where league_id = v_fixture.league_id)
     and exists (select 1 from rapid_cup_collections where box_type = 'winbox' and ref_id = p_fixture_id)
  then
    raise exception 'This match''s Winbox has already been collected, so its result can''t be cancelled here. Adjust wallets manually if a genuine correction is needed.';
  end if;

  update fixtures set
    played = false,
    home_score = null,
    away_score = null,
    pens_home = null,
    pens_away = null,
    played_at = null
  where id = p_fixture_id;
end;
$$;
