-- Rapid Cup — flips a full lobby from 'filling' to 'live': creates the
-- leagues/teams/fixtures rows and points the lobby at the new league.
--
-- league_type is set to 'fun', not 'cash' — 'cash' turns on the generic
-- proof-of-payment UI (MemberPaymentRow, payment_status flow) throughout
-- App.jsx/LeagueDetail.jsx, which Rapid Cup doesn't use: its own fee/payout
-- system runs entirely through rapid_cup_lobby_players + the future
-- Phase 3 payout RPC, not members.entry_fee/payment_status. members.entry_fee
-- also has a check(10-200) constraint that can't hold Rapid Cup's 0-400
-- range, so it's intentionally left null there — rapid_cup_lobby_players.entry_fee
-- stays the single source of truth for what each player staked.
--
-- Round-1 pairing is a simple random shuffle-and-pair of the 4 teams
-- (mirrors knockoutRound1 in src/App.jsx for n=4: no byes possible).
-- Later rounds (semis -> final) are generated by the existing
-- advanceKnockout flow once results come in (Phase 4/5 work) — this RPC
-- only needs to produce the opening 2 fixtures.
--
-- Race-safe: locks the lobby row and no-ops if it's already live/has a
-- league_id, so if two clients call this for the same lobby, only the
-- first does anything and both get back the same resulting lobby.
create or replace function generate_rapid_cup_bracket(p_lobby_id uuid)
returns rapid_cup_lobbies
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lobby rapid_cup_lobbies;
  v_league_id uuid;
  v_now timestamptz := now();
  v_due_at timestamptz;
  v_player record;
  v_team_ids uuid[] := '{}';
  v_new_team_id uuid;
begin
  select * into v_lobby from rapid_cup_lobbies where id = p_lobby_id for update;

  if v_lobby.id is null then
    raise exception 'Rapid Cup lobby % not found', p_lobby_id;
  end if;

  -- Already wired up (or not in a state to be) — return as-is, idempotent.
  if v_lobby.status <> 'filling' or v_lobby.league_id is not null then
    return v_lobby;
  end if;

  v_due_at := coalesce(v_lobby.started_at, v_now) + interval '4 hours';

  insert into leagues (name, format, knockout_legs, league_type, created_by_admin, starts_at)
  values ('Rapid Cup — ' || to_char(v_now, 'DD Mon HH24:MI'), 'knockout', 1, 'fun', true, v_now)
  returning id into v_league_id;

  -- One team per lobby player, named/phoned from their profile — random
  -- order so seeding isn't predictable from join order.
  for v_player in
    select lp.user_id, coalesce(p.efootball_username, 'Player ' || substr(lp.user_id::text, 1, 6)) as display_name, p.phone
    from rapid_cup_lobby_players lp
    left join profiles p on p.user_id = lp.user_id
    where lp.lobby_id = p_lobby_id
    order by random()
  loop
    insert into teams (league_id, name, phone)
    values (v_league_id, v_player.display_name, v_player.phone)
    returning id into v_new_team_id;

    v_team_ids := v_team_ids || v_new_team_id;

    insert into members (league_id, user_id, display_name, phone, team_id)
    values (v_league_id, v_player.user_id, v_player.display_name, v_player.phone, v_new_team_id);
  end loop;

  if array_length(v_team_ids, 1) <> 4 then
    raise exception 'Rapid Cup lobby % did not have exactly 4 players (had %)', p_lobby_id, array_length(v_team_ids, 1);
  end if;

  insert into fixtures (league_id, round, leg, stage, home_team_id, away_team_id, played, home_score, away_score, due_at, starts_at)
  values
    (v_league_id, 1, 1, 1, v_team_ids[1], v_team_ids[2], false, 0, 0, v_due_at, v_now),
    (v_league_id, 1, 1, 1, v_team_ids[3], v_team_ids[4], false, 0, 0, v_due_at, v_now);

  update rapid_cup_lobbies
  set status = 'live', league_id = v_league_id
  where id = p_lobby_id
  returning * into v_lobby;

  return v_lobby;
end;
$$;

grant execute on function generate_rapid_cup_bracket(uuid) to authenticated;
